### ISSUE TITLE
部分steam用户的头像无法加载出来

### ISSUE THREAD

**Issue by LiJunXiao** [One-Studio/CSGO-Toolbox#2]
部分的steam头像无法显示，其中mr72665899是淘宝购买的账号没有设置头像，keeping的账户头像是猫，POPAC的头像是龙珠的一个角色。其中第一个如果本身没有头像的账户能否考虑加入一个默认的头像？但是后两个无法显示，不清楚原因。
![image](https://user-images.githubusercontent.com/47941327/184473537-791e4dcd-5587-470e-9d1f-c010bfc92830.png)

**Comment by Purple-CSGO** [comment]
这里先读取本地的图片，然后尝试Steam主页的头像URL，可能是本地没有，云端的URL有问题

默认头像后面的更新加上
