### ISSUE TITLE
关于右上角图标

### ISSUE THREAD

**Issue by LiJunXiao** [One-Studio/CSGO-Toolbox#3]
![image](https://user-images.githubusercontent.com/47941327/184475000-f952953a-c248-48c0-96b2-897afe94ee82.png)
看上去真的让我以为是，切换用户的下拉箭头。。。。但其实是缩小。是否可以考虑更换一个更能表明意义的图标

**Comment by Purple-CSGO** [comment]
后面会换新的 ui，没有这种问题了
