### ISSUE TITLE
更新有问题

### ISSUE THREAD

**Issue by Iuleoo** [One-Studio/CSGO-Toolbox#8]
Get "https://api.upup.cool/repos/One-Studio/CSGO-Toolbox": read tcp 192.168.31.103:59165->172.67.197.36:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by Purple-CSGO** [comment]
API  用的是免费的 Cloudflare 服务，偶尔会有部分时间和地区遇到访问问题，整体上没有问题。

后面可能会加入多个不同的更新信息获取源以提高检查和更新的成功率
